# Generated by Django 4.0.3 on 2022-03-26 16:42

import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('unique_id', models.CharField(default=core.models.get_unique_id, editable=False, max_length=16, unique=True, verbose_name='Unique ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('unique_id', models.CharField(default=core.models.get_unique_id, editable=False, max_length=16, unique=True, verbose_name='Unique ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('numero', models.CharField(max_length=50, verbose_name='Numero')),
                ('correo', models.CharField(max_length=100, verbose_name='Correlo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('unique_id', models.CharField(default=core.models.get_unique_id, editable=False, max_length=16, unique=True, verbose_name='Unique ID')),
                ('monto', models.PositiveBigIntegerField(default=0, verbose_name='Monto')),
                ('fecha', models.DateField(default=datetime.date(2022, 3, 26), verbose_name='Fecha')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.categoria', verbose_name='Categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
