# Generated by Django 4.0.3 on 2022-03-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_cliente_numero_alter_gasto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='botcity_id',
            field=models.CharField(default=1, max_length=100, verbose_name='Bot city id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(max_length=100, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='concepto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Concepto'),
        ),
    ]
