# Generated by Django 4.0.3 on 2022-03-30 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 3, 30), verbose_name='Fecha'),
        ),
    ]
