# Generated by Django 4.0.3 on 2022-03-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_gasto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo'),
        ),
    ]
