# Generated by Django 4.0.3 on 2022-04-25 16:09

import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_cliente_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 4, 25), verbose_name='Fecha'),
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('unique_id', models.CharField(default=core.models.get_unique_id, editable=False, max_length=16, unique=True, verbose_name='Unique ID')),
                ('monto', models.PositiveBigIntegerField(default=0, verbose_name='Monto')),
                ('fecha', models.DateField(default=datetime.date(2022, 4, 25), verbose_name='Fecha')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.categoria', verbose_name='Categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
